### ISSUE TITLE
undici - next

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#2835]
TODO:

- [x] remove anti-pattern dispatcher hooks
- [x] remove old interceptor pattern (https://github.com/nodejs/undici/pull/2754)
- [x] new interceptor pattern (https://github.com/nodejs/undici/pull/2795)
- [ ] change so that dispatcher hooks take an options object instead of multiple arguments
- [ ] remove pipelining retries from core
- [ ] implement "idempotent" retry interceptor for pipeline resets
- [ ] implement "decompress" interceptor - #3255 
- [x] separate out http2
- [ ] #3275
- [ ] #3276
- [x] make dump investigate content-length to see if it's worth trying to read
- [x] move dump to interceptor - #3118 
- [ ] fix `Readable.setEncoding` issue (https://github.com/nodejs/undici/issues/1125#issuecomment-987724800)
- ~~[x] non-keep alive connections are not data safe~~
- ~~[ ] Should we split `onHeaders` into more fine-grained hooks? i.e. `onHeader(key, val)` and `onStatus(code, message)`?~~

Refs: https://github.com/nodejs/undici/issues/2722

**Comment by ronag** [comment]
@metcoder95

**Comment by metcoder95** [comment]
With `dispatcher hooks` do you refer to interceptors?

**Comment by ronag** [comment]
> With dispatcher hooks do you refer to interceptors?

It's methods on `Dispatcher`, i.e. `onHeaders`  etc...

**Comment by ronag** [comment]
Some of the above we can probably land on main.

**Comment by metcoder95** [comment]
>Should we split onHeaders into more fine-grained hooks? i.e. onHeader(key, val) and onStatus(code, message)?

This seems interesting, in theory, the HTTP response is split into three parts, the status line, headers and body; maybe we can follow this line?
See potential use cases, specially around stop request processing if the status is not the one expected

**Comment by ronag** [comment]
> This seems interesting, in theory, the HTTP response is split into three parts, the status line, headers and body; maybe we can follow this line?

it's actually headers first, then status and then body.

**Comment by metcoder95** [comment]
I'm working on the dump to interceptor, but I'm curious what do you have in mind for that API?

Also removing the legacy interceptor concepts from `next`, but is out of sync, should I open aim the branch anyways in this state?

**Comment by metcoder95** [comment]
cc: @ronag

**Comment by ronag** [comment]
I will sort the next branch sometime in the next two weeks. Just open or against current state.

**Comment by ronag** [comment]
> I'm working on the dump to interceptor, but I'm curious what do you have in mind for that API?

`.compose(interceptors.dump({ maxSize: 1024 * 1024 }))`

Something like that?

**Comment by PandaWorker** [comment]
It is also necessary to move the decompression of compressed data (gzip, deflate, br, zstd) into a separate interceptor

**Comment by ronag** [comment]
This plans need to be redone.

**Comment by ronag** [comment]
Creating a next branch etc is maybe not something I should be in charge of. I believe we should do the following things:

- remove old interceptor pattern
- remove maxRedirect defaults from agent etc... (apply interceptor in API methods instead)
- update llhttp

And that's it. I'll probably fork and apply things there for my own needs. Happy to help if someone else takes charge.

**Comment by metcoder95** [comment]
- [ ] Old pattern
- [ ] Replace max redirect with interceptor
- [ ] Update llhttp

**Comment by metcoder95** [comment]
I can help with this if support is needed 👍

**Comment by KhafraDev** [comment]
could we add https://github.com/nodejs/undici/pull/2728 and https://github.com/nodejs/undici/pull/2727 to next too?

**Comment by metcoder95** [comment]
Yeah, let's add them to next 👍

**Comment by ronag** [comment]
@metcoder95 Just to be clear. I won't be doing anything further with the next branch despite previous indications. Feel free to do whatever you want with it.

**Comment by artur-ma** [comment]
@ronag 
How about changing the `onHeaders` ? Now u get there just Buffer array, which requires each handler that needs headers to parse them (e.g retry handler, redirect handler)

So basically, we parse the headers multiple times, in each handler that needs headers
Also regarding removing `onConnect`, how to measure timing of acquiring the socket without it?
and the last one, removing `onBodySent` and wrapping it, is there an example for that?

Thanks

**Comment by ronag** [comment]
> How about changing the onHeaders ? Now u get there just Buffer array, which requires each handler that needs headers to parse them again and again(e.g retry handler, redirect handler)

This can solves with the following pattern that I've been using:

`onHeaders(statusCode, rawHeaders, resume, statusMessage, headers = parseHeaders(rawHeaders)) {`

**Comment by metcoder95** [comment]
Any specific reason why we added them unparsed?
