### ISSUE TITLE
2.0 TODO

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#347]
This is a meta list for stuff to look into before 2.0 release

- [x] https://github.com/mcollina/undici/pull/343
- [ ] https://github.com/mcollina/undici/issues/356
- [x] https://github.com/mcollina/undici/pull/348
- [ ] https://github.com/mcollina/undici/issues/350
- [x] Review busy and kResuming
- [x] Should `onConnect` be invoked again when retried due to head of line failure? (current behavior). **YES**
- [ ] Should abort signal and request timeout be moved out from core API and instead explicitly be implemented in `stream`, `pipeline`,`request`. https://github.com/mcollina/undici/pull/349
- [x] 100 coverage
- [x] Move "core" (client, request, errors, utils) into a core folder. (https://github.com/mcollina/undici/pull/351)
- [x] Is it possible for `onBody` to return nully?
- [x] Review `assert(!this.aborted)`.
- [ ] General review and test improvements.
- [x] Check benchmarks.
- [x] Add test for abort while in Pool queue.
- [ ] ...

3.0 

- [ ] rename `onInit` => `onPending` and `onConnect` => `onRunning`?
- [ ] Consider whether `Client` "busy" API needs to be changed or improved to allow further pipeline scheduling (i.e. Pool) experimentation in userland.

**Comment by ronag** [comment]
I don't think I will be able to sort out all potential semver major changes in a timely fashion. Would like to make a release once the bugs has been sorted out.

The way I see it we have the following things that might be breaking in addition to the existing PR's:

- `Client.busy` property
- `Client.'drain'` event
- `Client.dispatch` method

Would like to leave that to a 3.0 version. Should we mark them experimental in the meantime or is that unnecessary?

@mcollina wdyt

**Comment by mcollina** [comment]
I'm good with bumping as many semver-major we need :).

**Comment by ronag** [comment]
Made a 2.0 milestone for remaining issues.
